[package]
name = "regex-charclass"
version = "1.2.0"
edition = "2021"
rust-version = "1.63"
authors = ["Alexandre van Beurden"]
description = "Manipulate and convert regex character classes."
repository = "https://github.com/alexvbrdn/regex-charclass"
homepage = "https://github.com/alexvbrdn/regex-charclass"
documentation = "https://docs.rs/regex-charclass"
license = "MIT"
readme = "README.md"
keywords = ["regex", "unicode", "character-class", "set", "intersection"]
categories = ["text-processing", "data-structures"]
include = [
    "/src/**/*.rs",
    "/benches/**/*.rs",
    "/tests/**/*.rs",
    "/README.md",
    "/CHANGELOG.md",
    "/LICENSE",
]

[dependencies]
irange = "1.2"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
rand = "0.10"
regex = "1.11"
serde_json = "1.0"

[features]
serde = ["irange/serde", "dep:serde"]
ucd-16 = []
ucd-17 = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.bench]
codegen-units = 1

[[bench]]
name = "char_class"
harness = false
