#!/bin/bash
#
# Regenerate the Unicode tables for one version of the Unicode character database.
#
#     ./generate-classes.sh 17.0.0 [ucd-directory]
#
# The tables land in src/tokens/unicode/v17/, which the `ucd-17` Cargo feature selects.
# The UCD directory defaults to /tmp/ucd-<version>.
#
# It needs `ucd-generate` (`cargo install ucd-generate`) and a copy of the database,
# which is not vendored:
#
#     version=17.0.0
#     mkdir -p /tmp/ucd-$version
#     curl -LO https://www.unicode.org/Public/$version/ucd/UCD.zip
#     unzip UCD.zip -d /tmp/ucd-$version
#
# The generated files are exempt from rustfmt, so their formatting is whatever
# `ucd-generate` writes and a regeneration is a readable diff.
#
# Adding a version rather than refreshing one also means declaring its `ucd-*` feature
# in Cargo.toml, adding a block to src/tokens/unicode/mod.rs, and naming the version in
# the crate documentation and in CHANGELOG.md.

set -euo pipefail

version="${1:-}"
if ! [[ "$version" =~ ^([0-9]+)\.[0-9]+\.[0-9]+$ ]]; then
    echo "usage: $0 <unicode-version> [ucd-directory]   e.g. $0 17.0.0" >&2
    exit 2
fi
major="${BASH_REMATCH[1]}"

ucd="${2:-/tmp/ucd-$version}"
if [ ! -d "$ucd" ]; then
    echo "$ucd is not a directory; see the header of this script for the download." >&2
    exit 2
fi

out="$(dirname "$0")/src/tokens/unicode/v$major"
mkdir -p "$out"

ucd-generate general-category "$ucd" --chars --exclude surrogate > "$out/general_category.rs"
ucd-generate perl-word "$ucd" --chars > "$out/perl_word.rs"
ucd-generate property-bool "$ucd" --chars > "$out/property_bool.rs"
ucd-generate script "$ucd" --chars > "$out/script.rs"

cat > "$out/mod.rs" <<EOF
//! Unicode tables generated by \`ucd-generate\` from UCD $version.
//!
//! DO NOT EDIT THIS FILE. It is written by \`generate-classes.sh $version\`, like the tables
//! beside it, which are exempt from \`rustfmt\` and from \`clippy\` so that a regeneration
//! is a readable diff rather than a reformatting of the whole table.

/// The version of the Unicode character database these tables were generated from.
pub const UCD_VERSION: &str = "$version";

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod general_category;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod property_bool;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod script;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod perl_word;
EOF

echo "Wrote $out for UCD $version."
