//! Unicode tables generated by `ucd-generate` from UCD 17.0.0.
//!
//! DO NOT EDIT THIS FILE. It is written by `generate-classes.sh 17.0.0`, like the tables
//! beside it, which are exempt from `rustfmt` and from `clippy` so that a regeneration
//! is a readable diff rather than a reformatting of the whole table.

/// The version of the Unicode character database these tables were generated from.
pub const UCD_VERSION: &str = "17.0.0";

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod general_category;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod property_bool;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod script;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod perl_word;
