//! Unicode tables generated by `ucd-generate` from UCD 17.0.0.
//!
//! These files are written by `generate-classes.sh` and are not edited by hand, so they
//! are exempt from `rustfmt` and from `clippy`: reformatting them would make every
//! regeneration a diff of the whole table.

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod general_category;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod property_bool;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod script;

#[rustfmt::skip]
#[allow(clippy::all)]
pub mod perl_word;
